### PR TITLE
Hello Microverse Project

### PR DESCRIPTION
**Pull request by dave-prog**
## Hello Microverse Project

> This PR adds a project with the aim of learning how to set up a project using GitHub Actions, Linters, Basic HTML and CSS setup

#### Built With ❤Using:
- HTML
- CSS
- GitHub Workflows
- Linters (Stylelint, Webhint, Lighthouse) 

### In this project I:
- Added linter files to their respective folders
- Added a README file
- Wrote the message "Hello Microverse!" using HTML & CSS

### CODE REVIEW

**Comment by dave-prog** [comment]
Properly arranged and placed my linter folder and files as instructed by my code reviewer #4

**Review by divinecharlotte — CHANGES_REQUESTED** [review]
Hi @dave-prog   👋, 

## STATUS: REQUESTED CHANGES ♻️ 

Good job so far 👏 
There are some issues that you still need to work on to go to the next project but you are almost there!


### To Highlight 🎯 💡 

1. Good commit messages 👍 
2. Linters are passing 👍 

## Required Changes ♻️
☠️ I can see you deleted the previous branches where you had previous reviews which is not good kindly  next time do not create new PR for the project you've got already some previous reviews use the same branch to request the re-review, this will help reviewers to not get confused

- [ ] I can see you have done a lot of work on this PR👍 but let's make our Pull Request look more professional by giving them a description😉 kindly take a look at these points of requirements here you will get a guideline 👇 

qq 
- [ ] I can see that you tried to implement some required changes but still there some which are missing kindly go back to the changes requested by the [previous reviewer ](https://github.com/dave-prog/Hello-World/pull/3) and try to implement them all before you request another review and this will help you to save your time even in future projects make sure that you implement all the requested changes by the first reviewer before you request another which  will also  save reviews number from decreasing on your dashboard

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @divinecharlotte  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by bimbolabuari — COMMENTED** [review]
Hello @dave-prog  👋,

_This is an additional review as a result of the second opinion request._

- Kudos on working on this milestone, and welcome to Microverse 👍 
   - There are some changes that were requested by the previous code reviewer that I would suggest you implement and get your project approved.
      - Let's make your pull request summary descriptive 👍 

https://user-images.githubusercontent.com/66112760/219449263-412b2795-2909-4ee3-9dfc-eac256ad3508.mov

- 
     - Let's give your Pull request title a more descriptive one 
         -   Instead of `Linter Error Rectification`, what do you think about `add-hello-Microverse-project`? 🤔 

     - Let's also work on the README file as requested by the [first reviewer](https://github.com/dave-prog/Hello-World/pull/3#pullrequestreview-1298956539) 

Keep rocking 🚀!

**Review by MeqdamAlqudah — APPROVED** [review]
Hi @dave-prog , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
image

## Highlights 
:+1: Implement the last reviewer required changes
:+1: no linter errors
:+1: nice pull request description

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
